CREATE TABLE BANK_BANCAR (
  `ID` VARCHAR(64) NOT NULL,
  `CODE` VARCHAR(64) NOT NULL,
  `ID_CARD` VARCHAR(64) NOT NULL,
  `STATE` VARCHAR(64) NOT NULL,
  `AMT` DECIMAL NOT NULL,
  `BANK_OF_DEPOSIT` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODE_UNIQUE` (`CODE` ASC) VISIBLE);