CREATE TABLE BANK_CUSINF (
  `ID` VARCHAR(64) NOT NULL,
  `NAME` VARCHAR(64) NOT NULL,
  `ID_CARD` VARCHAR(64) NOT NULL,
  `PHONE` VARCHAR(64) NULL,
  `STATE` VARCHAR(64) NOT NULL,
  `TYPE` VARCHAR(64) NOT NULL,
  `PWD` VARCHAR(64) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_CARD_UNIQUE` (`ID_CARD` ASC) VISIBLE);