CREATE TABLE UAN_UNI 
(
  ID VARCHAR(64) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  CODE VARCHAR(64) NOT NULL,
  JOIN_IN_TIME TIMESTAMP NOT NULL,
  STATE VARCHAR(64) NOT NULL,
  TYPE VARCHAR(64) NOT NULL,
  PHONE VARCHAR(64) NOT NULL,
  ADDRESS VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);