drop table if exists BANK_BANCAR;
drop table if exists BANK_CUSINF;
drop table if exists UAN_CON;
drop table if exists UAN_UNI;
drop table if exists UAN_CAT;

CREATE TABLE BANK_BANCAR 
(
  ID VARCHAR(64) NOT NULL,
  CODE VARCHAR(64) NOT NULL,
  ID_CARD VARCHAR(64) NOT NULL,
  STATE VARCHAR(64) NOT NULL,
  AMT DECIMAL NOT NULL,
  BANK_OF_DEPOSIT VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);
  
CREATE TABLE BANK_CUSINF 
(
  ID VARCHAR(64) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  ID_CARD VARCHAR(64) NOT NULL,
  PHONE VARCHAR(64) NULL,
  STATE VARCHAR(64) NOT NULL,
  TYPE VARCHAR(64) NOT NULL,
  PWD VARCHAR(64) NULL,
  PRIMARY KEY (ID)
); 
  
CREATE TABLE UAN_CON (
  MASTERID VARCHAR(64) NOT NULL,
  CONTENT CLOB NOT NULL,
  PRIMARY KEY (MASTERID),
);
  
CREATE TABLE UAN_UNI 
(
  ID VARCHAR(64) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  CODE VARCHAR(64) NOT NULL,
  JOIN_IN_TIME TIMESTAMP NOT NULL,
  STATE VARCHAR(64) NOT NULL,
  TYPE VARCHAR(64) NOT NULL,
  PHONE VARCHAR(64) NOT NULL,
  ADDRESS VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE UAN_CAT 
(
  ID VARCHAR(64) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  BIGIN TIMESTAMP NOT NULL,
  END TIMESTAMP NOT NULL,
  AREAS VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);
